// 样式对象 - 包含所有组件样式
const styles = {
    // 全局容器
    appContainer: {
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
        backgroundColor: '#f8fafc',
    },
    // Header 样式
    header: {
        background: 'linear-gradient(135deg, #0f2b3d 0%, #1b4f6e 100%)',
        color: 'white',
        padding: '2rem 1.5rem',
        boxShadow: '0 10px 25px -5px rgba(0,0,0,0.1)',
    },
    headerContainer: {
        maxWidth: '1280px',
        margin: '0 auto',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '1rem',
    },
    logoArea: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    logoIcon: {
        fontSize: '2.2rem',
        filter: 'drop-shadow(2px 2px 4px rgba(0,0,0,0.2))',
    },
    title: {
        fontSize: '1.8rem',
        fontWeight: '700',
        letterSpacing: '-0.5px',
        margin: 0,
    },
    subtitle: {
        fontSize: '1rem',
        opacity: 0.9,
        background: 'rgba(255,255,255,0.2)',
        padding: '0.3rem 1rem',
        borderRadius: '40px',
        fontWeight: '400',
    },
    // 主内容区域
    mainContent: {
        flex: '1',
        maxWidth: '1280px',
        width: '90%',
        margin: '2rem auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '2.5rem',
    },
    // 新增课程卡片样式
    formCard: {
        backgroundColor: 'white',
        borderRadius: '24px',
        padding: '1.8rem 2rem',
        boxShadow: '0 8px 20px rgba(0,0,0,0.05)',
        border: '1px solid #eef2f6',
        transition: 'box-shadow 0.2s',
    },
    formTitle: {
        fontSize: '1.6rem',
        fontWeight: '600',
        marginBottom: '1.5rem',
        color: '#0f2b3d',
        display: 'flex',
        alignItems: 'center',
    },
    formGroup: {
        marginBottom: '1.4rem',
    },
    label: {
        display: 'block',
        fontWeight: '600',
        marginBottom: '0.5rem',
        color: '#334155',
        fontSize: '0.9rem',
    },
    input: {
        width: '100%',
        padding: '0.8rem 1rem',
        fontSize: '1rem',
        border: '2px solid #e2e8f0',
        borderRadius: '16px',
        outline: 'none',
        transition: 'border-color 0.2s, box-shadow 0.2s',
        fontFamily: 'inherit',
    },
    textarea: {
        width: '100%',
        padding: '0.8rem 1rem',
        fontSize: '1rem',
        border: '2px solid #e2e8f0',
        borderRadius: '16px',
        outline: 'none',
        fontFamily: 'inherit',
        resize: 'vertical',
    },
    charHint: {
        fontSize: '0.75rem',
        color: '#94a3b8',
        marginTop: '0.4rem',
        textAlign: 'right',
    },
    errorMsg: {
        color: '#e53e3e',
        fontSize: '0.8rem',
        marginTop: '0.4rem',
        fontWeight: '500',
    },
    submitBtn: {
        backgroundColor: '#2c7da0',
        color: 'white',
        border: 'none',
        borderRadius: '40px',
        padding: '0.9rem 1.8rem',
        fontSize: '1rem',
        fontWeight: '600',
        cursor: 'pointer',
        transition: 'background 0.2s, transform 0.1s',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        width: '100%',
        marginTop: '0.5rem',
        boxShadow: '0 4px 6px rgba(0,0,0,0.05)',
    },
    // 课程列表区域
    coursesSection: {
        marginTop: '0.5rem',
    },
    sectionHeader: {
        marginBottom: '1.5rem',
    },
    sectionTitle: {
        fontSize: '1.7rem',
        fontWeight: '600',
        color: '#1e293b',
        display: 'flex',
        alignItems: 'center',
    },
    courseCount: {
        fontSize: '1rem',
        fontWeight: '500',
        backgroundColor: '#e2e8f0',
        padding: '0.2rem 0.7rem',
        borderRadius: '30px',
        marginLeft: '12px',
        color: '#2d3748',
    },
    divider: {
        height: '4px',
        width: '70px',
        backgroundColor: '#2c7da0',
        borderRadius: '4px',
        marginTop: '8px',
    },
    // CourseList 网格布局
    courseListGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
        gap: '1.8rem',
    },
    // CourseCard 样式
    card: {
        backgroundColor: '#ffffff',
        borderRadius: '24px',
        padding: '1.5rem',
        boxShadow: '0 8px 20px rgba(0,0,0,0.04)',
        transition: 'transform 0.2s, box-shadow 0.2s',
        border: '1px solid #eef2f8',
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
    },
    cardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '1rem',
    },
    courseName: {
        fontSize: '1.35rem',
        fontWeight: '700',
        color: '#0f2b3d',
        margin: 0,
        lineHeight: 1.4,
        flex: 1,
        display: 'flex',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    deleteBtn: {
        backgroundColor: '#fee2e2',
        border: 'none',
        color: '#b91c1c',
        width: '36px',
        height: '36px',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        transition: 'background 0.2s, transform 0.1s',
        fontSize: '1rem',
        flexShrink: 0,
    },
    description: {
        color: '#475569',
        lineHeight: '1.55',
        margin: '0.8rem 0 1.2rem 0',
        fontSize: '0.95rem',
        flex: '1',
    },
    cardActions: {
        marginTop: 'auto',
        display: 'flex',
        justifyContent: 'flex-start',
    },
    learnBtn: {
        backgroundColor: '#eef2ff',
        border: 'none',
        padding: '0.6rem 1.2rem',
        borderRadius: '40px',
        fontWeight: '600',
        fontSize: '0.85rem',
        color: '#1e40af',
        cursor: 'pointer',
        transition: 'all 0.2s',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '5px',
    },
    emptyContainer: {
        textAlign: 'center',
        padding: '3rem 2rem',
        backgroundColor: '#ffffff',
        borderRadius: '28px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.02)',
        border: '1px dashed #cbd5e1',
    },
    emptyText: {
        fontSize: '1.1rem',
        color: '#64748b',
        marginTop: '0.5rem',
    },
    // Footer 样式
    footer: {
        backgroundColor: '#eef2f6',
        padding: '1.5rem',
        textAlign: 'center',
        marginTop: '2rem',
        borderTop: '1px solid #dce5ec',
    },
    footerText: {
        color: '#4a5568',
        fontSize: '0.85rem',
    }
};
